<?php


namespace Tests\Feature\Models\Video;


use App\Models\Video;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

abstract class BaseVideoTestcase extends TestCase
{
    use DatabaseMigrations;

    protected $data;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->data = [
          'title' => 'title',
          'description' => 'description',
          'year_launched' => 2010,
          'rating' => Video::RATING_LIST[0],
          'duration' => 90,

        ];
    }
}
